tpdir=`echom_clean.sh
# Uses only cp, find, rm — no rsync required
# Usage: bash copy_foam_clean.sh <source_dir> <dest_dir>
# ============================================================

SRC="$1"
DST="$2"

if [ -z "$SRC" ] || [ -z "$DST" ]; then
    echo "Usage: $0 <source_case_dir> <destination_dir>"
    exit 1
fi

echo "Copying $SRC -> $DST ..."
cp -r "$SRC" "$DST"

echo "--- Cleaning generated/compiled files ---"

# Parallel decomposition directories (processor0, processor1, ...)
find "$DST" -maxdepth 1 -type d -name 'processor*' -exec rm -rf {} +
echo "  [done] processor*/"

# Mesh generated by blockMesh / snappyHexMesh
find "$DST" -type d -name 'polyMesh' -exec rm -rf {} +
echo "  [done] constant/polyMesh/"

# Compiled coded boundary conditions / function objects
find "$DST" -maxdepth 1 -type d -name 'dynamicCode' -exec rm -rf {} +
echo "  [done] dynamicCode/"

# Post-processing results
find "$DST" -maxdepth 1 -type d -name 'postProcessing' -exec rm -rf {} +
echo "  [done] postProcessing/"

# Log files
find "$DST" -maxdepth 1 -name '*.log' -exec rm -f {} +
find "$DST" -maxdepth 1 -type d -name 'logs' -exec rm -rf {} +
echo "  [done] *.log / logs/"

# Time step directories — keep only 0/
# Matches integers, decimals, scientific notation e.g. 1  0.5  1e-3  2.5E+2
find "$DST" -maxdepth 1 -mindepth 1 -type d | while read -r dir; do
    base=$(basename "$dir")
    if [[ "$base" =~ ^[0-9]+([.][0-9]+)?([eE][+-]?[0-9]+)?$ ]] && [ "$base" != "0" ]; then
        rm -rf "$dir"
        echo "  [done] removed time dir: $base/"
    fi
done

echo ""
echo "=============================="
echo " Case structure after clean:"
echo "=============================="
find "$DST" -maxdepth 2 -type d | sort


# ============================================================
# SEPARATE: Remove atomizationFoam compiled binaries
# Run from your atomizationFoam source dir, or adjust
# SOLVER_SRC to the full path of your solver source.
# ============================================================

echo ""
echo "=============================="
echo " Cleaning atomizationFoam binaries"
echo "=============================="

# Adjust this path to wherever your solver source lives
SOLVER_SRC="$HOME/OpenFOAM/$USER/applications/solvers/atomizationFoam"

# 1. Object files inside Make/<platform>/ e.g. Make/linux64GccDPInt32Opt/
find "$SOLVER_SRC/Make" -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} +
echo "  [done] Make/<platform>/ object files"

# 2. Installed solver binary
#    $FOAM_USER_APPBIN = $HOME/OpenFOAM/<user>-<ver>/platforms/<plat>/bin
rm -f "$FOAM_USER_APPBIN/atomizationFoam"
echo "  [done] $FOAM_USER_APPBIN/atomizationFoam"

# 3. Any compiled libraries (if atomizationFoam has linked libs)
find "$FOAM_USER_LIBBIN" -name 'libatomizationFoam*' -exec rm -f {} +
find "$FOAM_USER_LIBBIN" -name 'libAtomization*'     -exec rm -f {} +
echo "  [done] $FOAM_USER_LIBBIN/libatomizationFoam*"

echo ""
echo "To recompile:"
echo "  cd $SOLVER_SRC && wmake" $PBS_JOBID | cut -f 1 -d .`
tempdir=$HOME/scratch/job$tpdir
mkdir -p $tempdir
cd $tempdir
exec > "$tempdir/master.log" 2>&1
set -x  
export PS4='+ $(date +%T) '   # prefix each traced line with HH:MM:SS
echo "copying" >> log
cp -R $PBS_O_WORKDIR/* .          # copies system/ along with everything else


module load openfoam2406
source /lfs/sware/OpenFOAM/OpenFOAM-2406/etc/bashrc
export PATH=/lfs/sware/gcc13.1.0/bin:/lfs/sware/openmpi405/bin:$PATH
export LD_LIBRARY_PATH=/lfs/sware/gcc13.1.0/lib64:/lfs/sware/gcc13.1.0/lib:/lfs/sware/openmpi405/lib:$LD_LIBRARY_PATH
export LIBRARY_PATH=/lfs/sware/gcc13.1.0/lib64:/lfs/sware/gcc13.1.0/lib:$LIBRARY_PATH
export WM_CC=/lfs/sware/gcc13.1.0/bin/gcc
export WM_CXX=/lfs/sware/gcc13.1.0/bin/g++

wclean applications/atomizationFoam
wclean src/libAtomization
rm -f /lfs/usrhome/btech/ed25b061/OpenFOAM/ed25b061-v2406/platforms/linux64GccDPInt32Opt/lib/libAtomization.so

export WM_CFLAGS="-L/lfs/sware/gcc13.1.0/lib64 -Wl,-rpath,/lfs/sware/gcc13.1.0/lib64"
export WM_CXXFLAGS="-L/lfs/sware/gcc13.1.0/lib64 -Wl,-rpath,/lfs/sware/gcc13.1.0/lib64"
export WM_LDFLAGS="-L/lfs/sware/gcc13.1.0/lib64 -Wl,-rpath,/lfs/sware/gcc13.1.0/lib64"


# Strip gcc9.2.0 / Intel / cuda include pollution so gcc13 uses its OWN headers
unset CPATH CPLUS_INCLUDE_PATH C_INCLUDE_PATH GCC_EXEC_PREFIX

echo "Allwmake" >> log
which g++
g++ --version          # must say 13.1.0, NOT 9.2.0
echo "$WM_CC $WM_CXX"a > log.allwmake
export WM_CC=/lfs/sware/gcc13.1.0/bin/gcc
export WM_CXX=/lfs/sware/gcc13.1.0/bin/g++

which g++
g++ --version          # must say 13.1.0, NOT 9.2.0
echo "$WM_CC $WM_CXX" >> log.allwmake

./Allwmake >> log.allwmake
echo "ran allwmake" >> log

export PATH=/lfs/usrhome/btech/ed25b061/OpenFOAM/ed25b061-v2406/platforms/linux64GccDPInt32Opt/bin:$PATH
export LD_LIBRARY_PATH=/lfs/usrhome/btech/ed25b061/OpenFOAM/ed25b061-v2406/platforms/linux64GccDPInt32Opt/lib:$LD_LIBRARY_PATH


cd run || { echo "ERROR: run/crossFlow not found under $tempdir" >> log; exit 1; }
